# Generated by Django 5.2.7 on 2025-10-14 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='WubiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sort_id', models.IntegerField()),
                ('date_init', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WubiWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_modify', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wubicategory')),
                ('user_init', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wubi_words_created', to=settings.AUTH_USER_MODEL)),
                ('user_modify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wubi_words_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
